"""Models for local scheduled Radar runs and in-app notifications."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator

from modules.radar.models import utc_now

ScheduleFrequency = Literal["hourly", "daily", "weekly", "custom_interval"]
ScheduledRunStatus = Literal["running", "success", "warning", "error", "skipped"]
NotificationSeverity = Literal["info", "success", "warning", "error"]


class RadarSchedule(BaseModel):
    """One local recurring Radar schedule."""

    model_config = ConfigDict(extra="forbid")

    schedule_id: str = Field(default_factory=lambda: uuid4().hex)
    name: str = Field(default="Radar agendado", min_length=1, max_length=160)
    enabled: bool = True
    wishlist_id: str | None = Field(default=None, max_length=120)
    source_ids: list[str] = Field(default_factory=list, max_length=50)
    keywords: list[str] = Field(default_factory=list, max_length=40)
    use_ai: bool = False
    use_profile_context: bool = True
    frequency: ScheduleFrequency = "daily"
    interval_minutes: int | None = Field(default=None, ge=60, le=10_080)
    timezone: str = Field(default="local", max_length=80)
    quiet_hours_start: str | None = Field(default=None, max_length=5)
    quiet_hours_end: str | None = Field(default=None, max_length=5)
    cooldown_minutes: int = Field(default=720, ge=0, le=43_200)
    min_match_score: int | None = Field(default=None, ge=0, le=100)
    min_ats_score: int | None = Field(default=None, ge=0, le=100)
    notify_on_new_matches: bool = True
    notify_on_score_threshold: bool = True
    last_run_at: datetime | None = None
    next_run_at: datetime | None = None
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("quiet_hours_start", "quiet_hours_end")
    @classmethod
    def validate_quiet_hour(cls, value: str | None) -> str | None:
        """Accept HH:MM values only."""
        if value is None or value == "":
            return None
        parts = value.split(":")
        if len(parts) != 2:
            raise ValueError("Use HH:MM para horario silencioso.")
        hour, minute = parts
        if not (hour.isdigit() and minute.isdigit()):
            raise ValueError("Use HH:MM para horario silencioso.")
        hour_int = int(hour)
        minute_int = int(minute)
        if not (0 <= hour_int <= 23 and 0 <= minute_int <= 59):
            raise ValueError("Horario silencioso invalido.")
        return f"{hour_int:02d}:{minute_int:02d}"


class RadarScheduledRun(BaseModel):
    """History entry for one scheduled Radar execution."""

    model_config = ConfigDict(extra="forbid")

    run_id: str = Field(default_factory=lambda: uuid4().hex)
    schedule_id: str
    started_at: datetime = Field(default_factory=utc_now)
    finished_at: datetime | None = None
    status: ScheduledRunStatus = "running"
    total_results: int = 0
    new_results: int = 0
    alerts_created: int = 0
    warnings: list[str] = Field(default_factory=list)
    error: str | None = None
    radar_run_id: str | None = None
    profile_context_used: bool = False
    manual: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)


class LocalNotification(BaseModel):
    """Local in-app notification generated by Radar and safe workflows."""

    model_config = ConfigDict(extra="forbid")

    notification_id: str = Field(default_factory=lambda: uuid4().hex)
    type: str = Field(default="radar_schedule", max_length=80)
    title: str = Field(min_length=1, max_length=180)
    message: str = Field(default="", max_length=1_000)
    severity: NotificationSeverity = "info"
    source: str = Field(default="radar", max_length=80)
    related_entity_type: str | None = Field(default=None, max_length=80)
    related_entity_id: str | None = Field(default=None, max_length=160)
    created_at: datetime = Field(default_factory=utc_now)
    read_at: datetime | None = None
    dismissed_at: datetime | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class RadarSchedulerStatus(BaseModel):
    """Runtime status returned by scheduler endpoints."""

    model_config = ConfigDict(extra="forbid")

    running: bool = False
    enabled_schedules: int = 0
    total_schedules: int = 0
    next_run_at: datetime | None = None
    due_schedules: int = 0
