/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TailorRouteImport } from './routes/tailor'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeStudioRouteImport } from './routes/resume-studio'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PublicExamsRouteImport } from './routes/public-exams'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MatchRouteImport } from './routes/match'
import { Route as JobRouteImport } from './routes/job'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GithubRouteImport } from './routes/github'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AtsRouteImport } from './routes/ats'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as ApplicationLabRouteImport } from './routes/application-lab'
import { Route as AiQualityRouteImport } from './routes/ai-quality'
import { Route as IndexRouteImport } from './routes/index'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorRoute = TailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeStudioRoute = ResumeStudioRouteImport.update({
  id: '/resume-studio',
  path: '/resume-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicExamsRoute = PublicExamsRouteImport.update({
  id: '/public-exams',
  path: '/public-exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const JobRoute = JobRouteImport.update({
  id: '/job',
  path: '/job',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationLabRoute = ApplicationLabRouteImport.update({
  id: '/application-lab',
  path: '/application-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AiQualityRoute = AiQualityRouteImport.update({
  id: '/ai-quality',
  path: '/ai-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-quality': typeof AiQualityRoute
  '/application-lab': typeof ApplicationLabRoute
  '/approvals': typeof ApprovalsRoute
  '/ats': typeof AtsRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/github': typeof GithubRoute
  '/help': typeof HelpRoute
  '/intelligence': typeof IntelligenceRoute
  '/interviews': typeof InterviewsRoute
  '/job': typeof JobRoute
  '/match': typeof MatchRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/public-exams': typeof PublicExamsRoute
  '/radar': typeof RadarRoute
  '/resume': typeof ResumeRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/tailor': typeof TailorRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-quality': typeof AiQualityRoute
  '/application-lab': typeof ApplicationLabRoute
  '/approvals': typeof ApprovalsRoute
  '/ats': typeof AtsRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/github': typeof GithubRoute
  '/help': typeof HelpRoute
  '/intelligence': typeof IntelligenceRoute
  '/interviews': typeof InterviewsRoute
  '/job': typeof JobRoute
  '/match': typeof MatchRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/public-exams': typeof PublicExamsRoute
  '/radar': typeof RadarRoute
  '/resume': typeof ResumeRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/tailor': typeof TailorRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-quality': typeof AiQualityRoute
  '/application-lab': typeof ApplicationLabRoute
  '/approvals': typeof ApprovalsRoute
  '/ats': typeof AtsRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/github': typeof GithubRoute
  '/help': typeof HelpRoute
  '/intelligence': typeof IntelligenceRoute
  '/interviews': typeof InterviewsRoute
  '/job': typeof JobRoute
  '/match': typeof MatchRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/public-exams': typeof PublicExamsRoute
  '/radar': typeof RadarRoute
  '/resume': typeof ResumeRoute
  '/resume-studio': typeof ResumeStudioRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/tailor': typeof TailorRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-quality'
    | '/application-lab'
    | '/approvals'
    | '/ats'
    | '/career'
    | '/dashboard'
    | '/evidence'
    | '/github'
    | '/help'
    | '/intelligence'
    | '/interviews'
    | '/job'
    | '/match'
    | '/portfolio'
    | '/privacy'
    | '/profile'
    | '/public-exams'
    | '/radar'
    | '/resume'
    | '/resume-studio'
    | '/settings'
    | '/sources'
    | '/tailor'
    | '/tracker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-quality'
    | '/application-lab'
    | '/approvals'
    | '/ats'
    | '/career'
    | '/dashboard'
    | '/evidence'
    | '/github'
    | '/help'
    | '/intelligence'
    | '/interviews'
    | '/job'
    | '/match'
    | '/portfolio'
    | '/privacy'
    | '/profile'
    | '/public-exams'
    | '/radar'
    | '/resume'
    | '/resume-studio'
    | '/settings'
    | '/sources'
    | '/tailor'
    | '/tracker'
  id:
    | '__root__'
    | '/'
    | '/ai-quality'
    | '/application-lab'
    | '/approvals'
    | '/ats'
    | '/career'
    | '/dashboard'
    | '/evidence'
    | '/github'
    | '/help'
    | '/intelligence'
    | '/interviews'
    | '/job'
    | '/match'
    | '/portfolio'
    | '/privacy'
    | '/profile'
    | '/public-exams'
    | '/radar'
    | '/resume'
    | '/resume-studio'
    | '/settings'
    | '/sources'
    | '/tailor'
    | '/tracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiQualityRoute: typeof AiQualityRoute
  ApplicationLabRoute: typeof ApplicationLabRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AtsRoute: typeof AtsRoute
  CareerRoute: typeof CareerRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceRoute: typeof EvidenceRoute
  GithubRoute: typeof GithubRoute
  HelpRoute: typeof HelpRoute
  IntelligenceRoute: typeof IntelligenceRoute
  InterviewsRoute: typeof InterviewsRoute
  JobRoute: typeof JobRoute
  MatchRoute: typeof MatchRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PublicExamsRoute: typeof PublicExamsRoute
  RadarRoute: typeof RadarRoute
  ResumeRoute: typeof ResumeRoute
  ResumeStudioRoute: typeof ResumeStudioRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  TailorRoute: typeof TailorRoute
  TrackerRoute: typeof TrackerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor': {
      id: '/tailor'
      path: '/tailor'
      fullPath: '/tailor'
      preLoaderRoute: typeof TailorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-studio': {
      id: '/resume-studio'
      path: '/resume-studio'
      fullPath: '/resume-studio'
      preLoaderRoute: typeof ResumeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-exams': {
      id: '/public-exams'
      path: '/public-exams'
      fullPath: '/public-exams'
      preLoaderRoute: typeof PublicExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job': {
      id: '/job'
      path: '/job'
      fullPath: '/job'
      preLoaderRoute: typeof JobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats': {
      id: '/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-lab': {
      id: '/application-lab'
      path: '/application-lab'
      fullPath: '/application-lab'
      preLoaderRoute: typeof ApplicationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-quality': {
      id: '/ai-quality'
      path: '/ai-quality'
      fullPath: '/ai-quality'
      preLoaderRoute: typeof AiQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiQualityRoute: AiQualityRoute,
  ApplicationLabRoute: ApplicationLabRoute,
  ApprovalsRoute: ApprovalsRoute,
  AtsRoute: AtsRoute,
  CareerRoute: CareerRoute,
  DashboardRoute: DashboardRoute,
  EvidenceRoute: EvidenceRoute,
  GithubRoute: GithubRoute,
  HelpRoute: HelpRoute,
  IntelligenceRoute: IntelligenceRoute,
  InterviewsRoute: InterviewsRoute,
  JobRoute: JobRoute,
  MatchRoute: MatchRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PublicExamsRoute: PublicExamsRoute,
  RadarRoute: RadarRoute,
  ResumeRoute: ResumeRoute,
  ResumeStudioRoute: ResumeStudioRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  TailorRoute: TailorRoute,
  TrackerRoute: TrackerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
